name: Daily Creative Prompt Generation
on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC, adjusts for most timezones
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Creative Prompt
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create directories first
          mkdir -p data
          mkdir -p apps/web/public/data
          # Meta-prompt for generating creative exercises
          PROMPT="Generate one unexpected creative stimulus - it could be anything: an object, a situation, a constraint, a weird fact, a made-up rule, or anything else that could spark ideas. Just give me the one thing, no explanation."

          curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
            -H "x-goog-api-key: $GEMINI_API_KEY" \
            -H 'Content-Type: application/json' \
            -X POST \
            -d "{
              \"contents\": [
                {
                  \"parts\": [
                    {
                      \"text\": \"$PROMPT\"
                    }
                  ]
                }
              ],
              \"generationConfig\": {
                \"responseMimeType\": \"application/json\",
                \"responseSchema\": {
                  \"type\": \"OBJECT\",
                  \"properties\": {
                    \"prompt\": { \"type\": \"STRING\" },
                    \"tags\": { \"type\": \"ARRAY\", \"items\": { \"type\": \"STRING\" } }
                  }
                }
              }
            }" > data/daily-prompt.json

      - name: Add metadata
        run: |
          # Add timestamp and ID for tracking
          jq '.candidates[0].content.parts[0].text | fromjson | . + {
            "generated_at": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "id": "'$(date +%s)'",
            "version": "web-v1"
          }' data/daily-prompt.json > apps/web/public/data/daily-prompt.json

      - name: Archive prompt (optional)
        run: |
          mkdir -p data/archive
          cp apps/web/public/data/daily-prompt.json "data/archive/prompt-$(date +%Y-%m-%d).json"

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add apps/web/public/data/  # Point to the right location
          git add data/archive/  # If you're keeping archives
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "✨ Daily creative prompt $(date +%Y-%m-%d)"
            git push
          fi
